app = "englishm-moq-relay"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
PORT = "443"
RUST_LOG="info"
# Qlog files for debugging (ephemeral - lost on restart)
QLOG_DIR="/tmp/qlog"
# Mlog files for MoQ Transport debugging (ephemeral - lost on restart)
MLOG_DIR="/tmp/mlog"

[experimental]
cmd = "./fly-relay.sh"

# UDP: raw pass-through to WebTransport on 443
[[services]]
  protocol = "udp"
  internal_port = 443
  [[services.ports]]
    port = 443

[services.concurrency]
hard_limit = 25
soft_limit = 20

# TCP: raw pass-through to HTTPS on 443 (TLS terminated by app)
[[services]]
  protocol = "tcp"
  internal_port = 443
  [[services.ports]]
    port = 443

[services.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20
