app = "englishm-moq-relay"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
PORT = "443"
RUST_LOG="info"
# Qlog files for debugging (ephemeral - lost on restart)
QLOG_DIR="/tmp/qlog"
# Mlog files for MoQ Transport debugging (ephemeral - lost on restart)
MLOG_DIR="/tmp/mlog"

[experimental]
cmd = "./fly-relay.sh"

[[services]]
internal_port = 4443
protocol = "udp"

[services.concurrency]
hard_limit = 25
soft_limit = 20

[[services.ports]]
port = "4443"

[[services]]
internal_port = 4443
protocol = "tcp"

# Note: Port 443 passes raw TCP without protocol handling.
# TLS termination is handled by the application itself.
[[services.ports]]
port = 443

[services.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20
