app = "englishm-moq-relay"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
PORT = "443"
RUST_LOG="info"
# Qlog files for debugging (ephemeral - lost on restart)
QLOG_DIR="/tmp/qlog"

[experimental]
cmd = "./fly-relay.sh"

[[services]]
internal_port = 4443
protocol = "udp"

[services.concurrency]
hard_limit = 25
soft_limit = 20

[[services.ports]]
port = "4443"
